apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    app: multi
spec:
  containers:
  - name: simple-app
    image: webapp
  - name: log-agent
    image: logger
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'git clone <some-repository-that-will-be-used-by-application> ;']