apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: ["sleep2.0"] ##this overrides the entrypoint in the docker file of the image
      args: ["10"]  ##this overrides the cmd filed
