apiVersion: v1
kind: ResourceQuota ##Used to limit resources at namepsace level
metadata:
  name: compute-quota
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "4" ## total 4 cpu can be requested
    requests.memory: 5Gi
    limits.cpu: "10" ## total limit across pods should be 10
    limits.memory: 10Gi