apiVersion: v1
kind: Config

current-context: my-kube-admin@my-kube-playground
clusters:
- name: my-kube-playground
  cluster:
    certificate-authority: ca.crt
    certificate-authority-data: <base64-string of the cert>
    server: https://my-kube:6443

contexts:
- name: my-kube-admin@mykube-playground
  context:
    user: my-kube-admin
    cluster: my-kube-playground
    namespace: admin

users:
- name: my-kube-admin
  user:
    client-certificate: admin.crt
    client-key: admin.key


