apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3 ## create pods untill it gets 3 completions
  parallelism: 3 ## allow 3 pods at once
  template:
    spec:
      containers:
        - name: math-add-job
          image: ubuntu
          command: ['expr', '3', '+', '2']
      restartPolicy: Never
