apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort ##for load balancer set this to LoadBalancer(only works in supported platforms)
  ports:
    - targetPort: 80 ##the port of the pod to which we route the request(if not provided will be same as port)
      port: 80 ##the port of the service object
      nodePort: 30008 ##the port on the node to bind
  selector:
    app: myapp
    type: front-end





