apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - "ReadOnlyMany" ##could be ReadWriteOnce or ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data