apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
  - verbs:
      - "list"
      - "get"
    resources:
      - "pods"
    apiGroups:
      - ""
  - verbs:
      - "create"
    resources:
      - "ConfigMap"
    apiGroups:
      - ""
